export const GET_OPEN_TICKETS = "GET_OPEN_TICKETS";
export const GET_CLOSED_TICKETS = "GET_CLOSED_TICKETS";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const GET_TICKET_INFORMATION = "GET_TICKET_INFORMATION";

export const SEARCH_FOR_TICKET = "SEARCH_FOR_TICKET";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const CLOSE_TICKET = "CLOSE_TICKET";
export const REOPEN_TICKET = "REOPEN_TICKET";

export const GET_HISTORY = "GET_HISTORY";
export const ADD_HISTORY = "ADD_HISTORY";

export const GET_ALL_TAGS = "GET_ALL_TAGS";
export const GET_ALL_TAGS_FOR_OPEN_TICKETS = "GET_ALL_TAGS_FOR_OPEN_TICKETS";
export const GET_ALL_TAGS_CLOSED_TICKETS = "GET_ALL_TAGS_CLOSED_TICKETS";
export const GET_TAGS = "GET_TAGS";
export const ADD_TAG = "ADD_TAG";
export const DELETE_TAG = "DELETE_TAG";

export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_DARK_THEME = "SET_DARK_THEME";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
