export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const GET_TICKET_INFORMATION = "GET_TICKET_INFORMATION";

export const SEARCH_FOR_TICKET = "SEARCH_FOR_TICKET";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const CLOSE_TICKET = "CLOSE_TICKET";

export const GET_HISTORY = "GET_HISTORY";
export const ADD_HISTORY = "ADD_HISTORY";
